BUILD_USER_HOME=${BUILD_USER_HOME:-"/root"}

NGINX_APP_NAME="nginx"

APP_NAME="${NGINX_APP_NAME}"

LATEST_NGINX_VERSION="1.26.2"

LATEST_NGINX_RELEASE="1"
RELEASE=${RELEASE-"1"}

APP_VERSION=${APP_VERSION:-${LATEST_NGINX_VERSION}}

DIST=${DIST:-"el8"}

ARCH=${ARCH:-"x86_64"}
